### ISSUE TITLE
Minor typo in documentation

### ISSUE THREAD

**Issue by RamRS** [theislab/zellkonverter#100]
Hi,

There is a minor typo in the first line of your documentation for the `AnnData2SCE()`/`SCE2AnnData()` functions. It stands out because it's the first line encountered on this page: https://theislab.github.io/zellkonverter/reference/index.html

The line says "Convert AnnData between and"; it should be "Convert between AnnData and"

https://github.com/theislab/zellkonverter/blob/253179e9d05a309f366dbc06148017886221623c/R/AnnData2SCE.R#L1

**Comment by lazappi** [comment]
Thanks! I'll add this to the next patch.
