### ISSUE TITLE
CITE-Seq Support for Zellkonverter

### ISSUE THREAD

**Issue by viktorzou** [theislab/zellkonverter#110]
Hi @lazappi,
thx for the great package. I want to use Zellkonverter for conversion of CITESeq data, h5ad -> SCE -> Seurat. I am having trouble finding the Protein Data, where I would expect them (ADT Assay in Seurat object). Is it supported and if yes, where will I find the data or do I have to add the data manually after SC Conversion?
best regards
Viktor

**Comment by viktorzou** [comment]
so I found out, that when using Zellkonverter readH5AD() with layers = TRUE, I do get the ADT informatation, but it is not a seperate assay, but appended at the end of the rownames... Is there any possibility to have it seperated as an assay or do I have to seperate it manually?

**Comment by lazappi** [comment]
This isn't really a **{zellkonverter}** issue, it's just that `AnnData` is not designed for multimodal data. Where additional features are stored and how they are converted depends on where the person who created the object decided to store them. In this case it sounds like they were just concatenated to the gene expression matrix.

**Comment by viktorzou** [comment]
yeah.. it seems to be this way. Thank you. I will manually create the assays, that are needed :)
