### ISSUE TITLE
Values in SCE metadata are lost

### ISSUE THREAD

**Issue by lucas02061** [theislab/zellkonverter#115]
I have tried to use the following function to convert data from SCE to H5AD format. However, the metadata after using zellkonverter is lost. Example, if I try to write a dataset and then read it again, the metadata is empty when I read it. Is there a way to solve this? Potentially another name/location to store this information? Thanks.
zellkonverter::writeH5AD(sce = SCE, file = file_path)

Cheers,
Lucas

**Comment by lazappi** [comment]
Hi @lucas02061 

To answer this, I would need to know more about what information is lost and the output you get when using `writeH5AD()`. A small reproducible example would also be very helpful.

**Comment by lucas02061** [comment]
I found out this was a mistake with SCE not zellkonverter. Sorry for the inconvenience.
