### ISSUE TITLE
Conversion Error: Conversion from numpy array type 20 is not supported with reticulate >= 1.36.0

### ISSUE THREAD

**Issue by zipy124** [theislab/zellkonverter#116]
When using the same dataset as in #96 , I get an error that numpy array type 20 is not supported for the uns item of rank_genes_groups and its related data.

lupus <- readH5AD("E:\\martha\\GSE174188_CLUES1_adjusted.h5ad")

When excluding these uns items I still cannot read the file, but have opened a separate issue for that.

**Comment by zipy124** [comment]
Just tried with the same versions as the fix landed for https://github.com/theislab/zellkonverter/issues/96 that is v1.11.1 with R 4.2.0 and it works, so this is presumably a regression since then.

**Comment by lazappi** [comment]
😿 I thought had fixed this but maybe later changes broke it again. Can you please:

- Tell me which version of R, **{zellkonverter}** and **{reticulate}** doesn't work
- Which version of **{reticulate}** you have installed when it works
- Try running it with the failing version, but set `readH5AD(..., version = "0.8.0")`

**Comment by lazappi** [comment]
I have been getting errors/warnings about this now and looking in to it, it seems like something changed in **{reticulate}** v`1.36.0` that broke the previous fix. I have opened an issue about it https://github.com/rstudio/reticulate/issues/1613 but in the meantime a temporary fix would be to downgrade to **{reticulate}** v`1.35.0`.

**Comment by lazappi** [comment]
Closing this as **{reticulate}** `v1.38.0` is now available on CRAN.
