### ISSUE TITLE
"Error in .Call2("C_h5mread", filepath, name, starts, counts, noreduce,  :    H5Dread() returned an error"

### ISSUE THREAD

**Issue by zipy124** [theislab/zellkonverter#117]
I'm using the same dataset as in #96 using the same settings, however It seems to fail on reading the x matrix using HDF5Array. 

lupus <- readH5AD("GSE174188_CLUES1_adjusted.h5ad",verbose=TRUE,uns=c("umap","pca","neighbors"),raw=TRUE,use_hdf5=TRUE)

uns is used here to prevent an error of "Conversion Error: Conversion from numpy array type 20 is not supported" on reading the uns/rank_genes_groups as specified in my other bug report #116 .

When using use_hdf5=FALSE I get a matrix size error with size 1999 x 1.2M not matching names dim size of 1.2M.

**Comment by zipy124** [comment]
Just tried with the same versions as the fix landed for #96 that is v1.11.1 with R 4.2.0 and it works, so this is presumably a regression since then.

**Comment by lazappi** [comment]
I'm not so sure what is happening with this one. The error you get when `use_hdf5 = FALSE` could be because the dataset is too large for R, but I don't know what the main error is. I'm hoping it will make more sense when I think into the other problem.

**Comment by jcapelladesto** [comment]
Hi,

I also got a similar error:

> Error in .Call2("C_h5mread", filepath, name, starts, counts, noreduce,  : 
>   H5Dread() returned an error

Could this be potentially solved using reticulate 1.35 as you mentioned in this issue (https://github.com/theislab/zellkonverter/issues/116) ?

**Comment by lazappi** [comment]
I'm not sure this is related but it could be worth trying. More information about the versions etc. you are using would be helpful.

**Comment by lazappi** [comment]
@zipy124 @jcapelladesto Is this still an issue? If not, I will close this.

**Comment by jcapelladesto** [comment]
You may close it, as I have stopped working on h5 format. Thank you for
your interest.

Missatge de Luke Zappia ***@***.***> del dia dv., 4 d’oct.
2024 a les 13:45:
