### ISSUE TITLE
Unable to configure environment

### ISSUE THREAD

**Issue by liuweihahaha** [theislab/zellkonverter#118]
Hi,
When I downloaded the zellkonverter package, and I already downloaded anaconda, I kept getting errors when I called readH5AD, my network was fine.The following is an error

zellkonverter::readH5AD("A5_345_S1Aligned.sortedByCoord.out.h5ad")
trying URL 'https://repo.anaconda.com/miniconda/Miniconda3-py39_4.12.0-Linux-x86_64.sh'
Error in download.file(url, fname, mode = "wb") : 
  cannot open URL 'https://repo.anaconda.com/miniconda/Miniconda3-py39_4.12.0-Linux-x86_64.sh'

**Comment by lazappi** [comment]
Hi @liuweihahaha 

Installing the Python environments is handled by **{basilisk}** so this question might be more appropriate there.

I know you said your network was fine but it does seem like R can't connect for some reason. You could test this just with `download.file('https://repo.anaconda.com/miniconda/Miniconda3-py39_4.12.0-Linux-x86_64.sh')`. If that doesn't work then it is something to do with your connection, not anything in **{zellkonverter}**/**{basilisk}**.

**Comment by lazappi** [comment]
@liuweihahaha I am closing this issue as I don't think it's a **{zellkonverter}** problem
