### ISSUE TITLE
After running sc.experimental.pp.recipe_pearson_residuals, I encountered a warning when running sc.tl.rank_genes_groups.

### ISSUE THREAD

**Issue by Always-Stude** [theislab/zellkonverter#121]
After I run sc.experimental.pp.recipe_pearson_residuals(adata, n_top_genes=2000, inplace=True), I cannot run sc.pl.highly_variable_genes(adata), and when I run sc.tl.rank_genes_groups(adata, 'leiden', method='wilcoxon'), a warning is issued: "It seems you use rank_genes_groups on the raw count data. Please logarithmize your data before calling rank_genes_groups." What does this mean, and how can I resolve it?

**Comment by Always-Stude** [comment]
@mtmorgan @rcannood @jwokaty @nturaga

**Comment by lazappi** [comment]
This issue is not related to **{zellkonverter}**. If you need help with this package please open a new issue and please do not tag people directly as it sends unnecessary notifications.
