### ISSUE TITLE
Factor with missing levels lead to one-off errors

### ISSUE THREAD

**Issue by const-ae** [theislab/zellkonverter#122]
Hi,

I am currently trying to read an h5ad file that has a column called `"condition"` which is stored as a categorical (I think that means that it was saved with AnnData version < 0.7.0).

Currently the implementation in [`.read_dim_data`](https://github.com/theislab/zellkonverter/blob/devel/R/read.R#L368) takes the integers, converts them to a factor, and overrides the levels:
```r
levels <- as.vector(rhdf5::h5read(file, file.path(path, "__categories", cat_name)))
out_cols[[cat_name]] <- factor(out_cols[[cat_name]])
levels(out_cols[[cat_name]]) <- levels
```

This code fails if one of the factor level is unused:
``` r
# The conditions were: A, C, C, A, A, A, A (i.e., no B)
out_cols <- list(condition = c(0, 2, 2, 0, 0, 0, 0))

levels <- c("a", "b", "c")
out_cols[["condition"]] <- factor(out_cols[["condition"]])
levels(out_cols[["condition"]]) <- levels

# After parsing: the conditions appears as 5x A and 2x B!!
table(out_cols[["condition"]])
#> 
#> a b c 
#> 5 2 0
```

<sup>Created on 2024-08-19 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

The problem is very easy to miss because R **silently** replaces the levels even though the length of the old and new levels are different.

--------

One way to fix the implementation would be to write:
``` r
out_cols[["condition"]] <- factor(levels[out_cols[["condition"]]+1L], levels = levels)

table(out_cols[["condition"]])
#> 
#> a b c 
#> 5 0 2
```

<sup>Created on 2024-08-19 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by lazappi** [comment]
Hi @const-ae 

Thanks for the issue. It looks like you are using the R reader? I'm a bit rusty on how this works but I think you are probably right. Any chance you would be interested in submitting a PR with this change?

**Comment by const-ae** [comment]
>  It looks like you are using the R reader?

Yes exactly. 

> Any chance you would be interested in submitting a PR with this change?

Sorry, I currently don't have the bandwidth as I am trying to wrap up some revisions before moving to London next week.

**Comment by lazappi** [comment]
This should be fixed in devel now (`v1.15.3`) and in the next release

**Comment by const-ae** [comment]
Thanks for picking this up :)

I just looked at the code change and wondered if you changed anything else to make sure that `out_cols[[cat_name]]` is not just an integer vector? Because if it is integers, then the new code produces NA's:

``` r
out_cols <- list(condition = c(0, 2, 2, 0, 0, 0, 0))
levels <- c("a", "b", "c")
factor(out_cols[["condition"]], levels = levels)
#> [1] <NA> <NA> <NA> <NA> <NA> <NA> <NA>
#> Levels: a b c
```

<sup>Created on 2024-10-04 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by lazappi** [comment]
Ugh, maybe I didn't test this properly. I'll take another look and check if this can happen. Thanks for letting me know!

**Comment by lazappi** [comment]
You were right, that was a silly mistake. Something closer to your original suggestions (which I think I have properly tested) is on GitHub and will be in the next release.

**Comment by const-ae** [comment]
Great. Thank you for your efforts in maintaining this excellent package :)
