### ISSUE TITLE
H5MU to Multi Assay Experiment object

### ISSUE THREAD

**Issue by JHYSiu** [theislab/zellkonverter#130]
Hi 

Thanks for a lovely package. I was just wondering if there's anything in the pipeline regarding converting a H5MU (multi-modal object) to MAE (multi assay experiment). 

Thanks!

**Comment by lazappi** [comment]
You should have a look at the Bioconductor  [**{MuData}**](https://www.bioconductor.org/packages/release/bioc/html/MuData.html) package. We don't plan to include MuData objects/files in **{zellkonverter}**.
