### ISSUE TITLE
unable to install zellkonverter

### ISSUE THREAD

**Issue by bromleyjd** [theislab/zellkonverter#30]
<img width="1247" alt="Screen Shot 2020-12-19 at 3 32 10 PM" src="https://user-images.githubusercontent.com/60758390/102698974-5d2b6600-420f-11eb-821d-0ff4f9502a2c.png">

**Comment by LTLA** [comment]
Bioconductor/BiocManager#85

**Comment by lazappi** [comment]
As the issue Aaron linked to says **zellkonverter** is only available from Bioconductor 3.12. You can use `BiocManager::install(version = "3.12")` upgrade but be aware this will update all your Bioconductor packages.
