### ISSUE TITLE
Port backed='r' into release

### ISSUE THREAD

**Issue by LTLA** [theislab/zellkonverter#33]
29847ebb51fc315b0caba4ffc7c58f5708bed1fc fixes a bug whereby you can't load backed matrices that you don't have write access to, as AnnData defaults to RW mode in the Python-level constructor. Can this be ported to release?

**Comment by lazappi** [comment]
Done. Sorry should have asked about that the first time.

**Comment by lazappi** [comment]
So I failed at doing this the first time. Turns out you need to add all the commits from the PR or the checks will fail 🤦🏻. Should be fixed with v1.0.2.
