### ISSUE TITLE
The first time calling writeH5AD installs more dependencies

### ISSUE THREAD

**Issue by hisplan** [theislab/zellkonverter#54]
Hi,

I've installed the package via `BiocManager::install("zellkonverter")`, but then the first time when I tried to call the `writeH5AD` function, it actually started to install more dependencies such as miniconda, h5py, scipy, and etc. My end goal is including `zellkonverter` inside a docker image. It would be great if there is a way to install everything via `BiocManager::install("zellkonverter")` including all the necessary runtime dependencies. Or I'm looking for any solution that allows me to avoid additional download/installation during the "runtime".

Based on the console output, it looks like it is trying to install everything under this conda environment: `/root/.cache/R/basilisk/1.4.0/zellkonverter/1.2.0/zellkonverterAnnDataEnv`, even if I specified a specific python/environment to use in the beginning as shown below:

```
use_condaenv(
  condaenv = "/opt/conda/envs/workspace",
  conda = "/opt/conda/bin/python",
  required = TRUE
)
```

Any solution? Thanks!

**Comment by LTLA** [comment]
Have a look at `BASILISK_USE_SYSTEM_DIR` in the [**basilisk** vignette](https://bioconductor.org/packages/release/bioc/vignettes/basilisk/inst/doc/motivation.html#modifying-environment-variables).

**Comment by hisplan** [comment]
Thank you! This is exactly what I was looking for. Closing this.
