### ISSUE TITLE
writeH5AD() coerces character vectors to factors

### ISSUE THREAD

**Issue by lazappi** [theislab/zellkonverter#6]
This prevents a perfect round-trip from R to `.h5ad` and back.

I suspect this is due to the `anndata` export function but it may be possible to override the default behaviour.

Originally mentioned in #5

**Comment by lazappi** [comment]
After consulting with people this is indeed part of how `anndata` writes `.h5ad` files and there is no way to turn it off.

One workaround would be to store column types somewhere and check them in `readH5AD()` but that's maybe a bit hacky and not sure if it's worth the effort.

**Comment by LTLA** [comment]
Probably not. Best just to make a nice list of "known round-trip losses" in `?AnnData2SCE` and leave it at that.
