### ISSUE TITLE
Error in installConda() : conda installation failed with status code '2'

### ISSUE THREAD

**Issue by maqingyue** [theislab/zellkonverter#89]
Hello, thank you very much for developing this software. I encountered the following error while running writeH5AD locally. How can I correct it?

> writeH5AD(sce, file = 'D:/filtered_featured_bc_matrix.h5ad')
Error in installConda() : conda installation failed with status code '2'

**Comment by lazappi** [comment]
Hi @maqingyue

This seems to be an issue with creating the conda environment which is handled by the **{basilisk}** package. It's probably better to ask the question there, unless @LTLA you prefer to help here?

**Comment by lazappi** [comment]
Closing this has I think it is an upstream issue and has hopefully been resolved.
